FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3 python3-pip
RUN /usr/bin/python3 -m pip install --upgrade pip
COPY . /app
WORKDIR /app
RUN pip3 install --no-cache-dir -r /app/requirements.txt
CMD ["/usr/bin/python3", "/app/main.py"]